export const RULES = {
  soccer: {
    name: 'Fußball',
    icon: '⚽',
    structure: '2 × 45 Min. Spielzeit + 15 Min. Halbzeitpause',
    periods: 2,
    periodLabel: 'Halbzeit',
    scoring: 'Tore. Ball muss vollständig die Torlinie überqueren.',
    basics: [
      '11 Spieler pro Team (10 Feldspieler + Torwart)',
      'Nur Torwart darf Ball im eigenen Strafraum mit Händen berühren',
      'Abseits: Angreifer darf bei Abspiel nicht hinter vorletztem Verteidiger stehen',
      'Fouls: Direkter Freistoß / Elfmeter (im Strafraum) / Gelbe/Rote Karte',
      'Einwurf: Beide Hände, Ball hinter Kopf, beide Füße am Boden',
      'Eckball: Ball über Torlinie → Ecke; über Seitenlinie → Einwurf',
      'Verlängerung & Elfmeterschießen bei Gleichstand (Pokalmodus)',
    ],
    tip: '90 Min. einstellen → Halbzeit nach 45 Min. drücken → Spielstand notiert + Pause startet.',
  },
  basketball: {
    name: 'Basketball',
    icon: '🏀',
    structure: '4 × 10 Min. (FIBA) oder 4 × 12 Min. (NBA)',
    periods: 4,
    periodLabel: 'Viertel',
    scoring: '2 Punkte (normaler Korb), 3 Punkte (hinter der 3-Punkte-Linie), 1 Punkt (Freiwurf)',
    basics: [
      '5 Spieler pro Team auf dem Feld',
      'Dribbling: Ball muss ständig geprellt werden, außer beim Stoppen oder Werfen',
      'Schritte: Maximal 2 Schritte ohne Dribbling (Schrittregel)',
      'Doppeldribbling: Ball darf nach Stopp nicht erneut gedribbelt werden',
      '3-Sekunden-Regel: Angreifer darf max. 3 Sek. in gegnerischer Zone stehen',
      '8-Sekunden-Regel: Ball muss innerhalb 8 Sek. in gegnerische Spielhälfte',
      '24-Sekunden-Shot-Clock (FIBA): Team muss innerhalb 24 Sek. einen Korbwurf ausführen',
      'Persönliche Fouls: 5 (FIBA) oder 6 (NBA) Fouls → Spieler scheidet aus',
      'Auszeit: 2 Auszeiten pro Halbzeit, je 1 Min.',
    ],
    tip: '40 Min. einstellen → nach jedem Viertel (10 Min.) auf "Halbzeit" drücken.',
  },
  volleyball: {
    name: 'Volleyball',
    icon: '🏐',
    structure: 'Best of 5 Sätze. Satz bis 25 Punkte (5. Satz bis 15). Mindest-Zwei-Punkte-Vorsprung.',
    periods: 5,
    periodLabel: 'Satz',
    scoring: 'Jeder Ballkontakt, bei dem der Ball auf dem Boden des Gegners aufkommt oder Gegner ins Aus spielt.',
    basics: [
      '6 Spieler pro Team auf dem Feld (4 Vorderreihe, 2 Hinterreihe)',
      'Max. 3 Berührungen pro Team bevor der Ball über das Netz muss',
      'Rotation: Alle Spieler rotieren im Uhrzeigersinn nach eigenem Aufschlag-Gewinn',
      'Libero: Spezialposition, darf in Hinterreihe für jeden tauschen (anderes Trikot)',
      'Netzberührung: Beim Spielzug verboten',
      'Block zählt nicht als eine der 3 Berührungen',
      'Aufschlag aus der Aufschlagzone (hinter Grundlinie)',
      'Aufschlag muss innerhalb 8 Sekunden nach Pfeiff ausgeführt werden',
    ],
    tip: 'Kein Zeitlimit → Punkte nach jedem Rally eintragen. Satz vorbei → Halbzeit-Button für Satzwechsel.',
  },
  voelkerball: {
    name: 'Völkerball',
    icon: '🎯',
    structure: '2 × 10 Min. + 5 Min. Pause (Schulsport-Variante)',
    periods: 2,
    periodLabel: 'Halbzeit',
    scoring: 'Punkte für jeden eliminierten Gegner (oder nach Spieleranzahl am Ende)',
    basics: [
      '2 Teams stehen sich auf geteiltem Spielfeld gegenüber',
      'Spieler abschlagen: Ball direkt am Körper treffen (kein Aufpraller zählt)',
      'Getroffener Spieler scheidet aus und stellt sich hinter die gegnerische Grundlinie (Außenfeld)',
      'Vom Außenfeld können Spieler ins Innenfeld zurück, wenn sie einen Ball fangen',
      'Ball fangen: Direktfang ohne Bodenberührung → Werfer scheidet aus, Fänger darf zurück',
      'Doppeldecker: Abwurf vom Außenfeld über Innenfeldspieler in gegnerisches Innenfeld erlaubt',
      'Gewonnen: Team mit letztem Spieler im Innenfeld gewinnt',
      'Schulsport: Zeitlimit → Team mit mehr Spielern im Innenfeld gewinnt',
    ],
    tip: '20 Min. einstellen → Halbzeitpause nach 10 Min. → Teams wechseln Seite.',
  },
  laufsport: {
    name: 'Laufsport',
    icon: '🏃',
    structure: 'Zeitmessung per Stoppuhr. Kein Zeitlimit, keine Punkte.',
    periods: 1,
    periodLabel: 'Lauf',
    scoring: 'Schnellste Zeit gewinnt. Runden/Splits mit Stoppuhr-Runden-Funktion.',
    basics: [
      'Stoppuhr-Modus empfohlen (im Tools-Bereich)',
      'Lappen-Funktion für Zwischen- und Rundenzeiten',
      'Gruppenvergleich: Beide Gruppen gleichzeitig mit getrennten Stoppuhren messen',
      'Staffellauf: Einzelzeiten addieren oder längste Gesamtzeit messen',
      '100m / 400m / 800m / 1000m: Läufer starten nach Signal, Zeit läuft bis Zieleinlauf',
      'Hindernislauf: Zeitmessung wie normaler Lauf, Plus-Strafsekunden für umgeworfene Hürden',
    ],
    tip: 'Tools-Screen → Stoppuhr mit Lap-Funktion für Rundenzeiten. Gruppen-Modus: 2 Stoppuhren parallel.',
  },
  schulsport: {
    name: 'Schulsport',
    icon: '🏫',
    structure: 'Flexibel konfigurierbar. Ideal für nicht standardisierte Schulspiele.',
    periods: 2,
    periodLabel: 'Halbzeit',
    scoring: 'Punkte oder Tore nach eigenen Regeln.',
    basics: [
      'Eigene Regeln festlegen, App als Zähl-Assistent nutzen',
      'Teamgröße und Spielzeit frei wählbar',
      'Halbzeit nach Bedarf drücken',
      'Auszeit für kurze Pausen nutzen',
    ],
    tip: 'Preset bearbeiten und eigene Teambezeichnungen, Farben und Spielzeit eintragen.',
  },
  handball: {
    name: 'Handball',
    icon: '🤾',
    structure: '2 × 30 Min. + 10 Min. Halbzeitpause',
    periods: 2,
    periodLabel: 'Halbzeit',
    scoring: 'Tore (Ball muss vollständig die Torlinie überqueren)',
    basics: [
      '7 Spieler pro Team (6 Feldspieler + Torwart)',
      'Torwart: Einziger, der im Torraum (6-Meter-Kreis) spielen darf',
      '3-Schritt-Regel: Max. 3 Schritte ohne Dribbling; alternativ max. 3 Sekunden halten',
      'Doppeldribbling: Nach Stopp nicht erneut dribbeln',
      'Torraum: Nur Torwart im Kreis. Angreifer darf nach Torschuss in Kreis gleiten.',
      'Freiwurf (9-Meter): Bei groben Fouls außerhalb Strafraum',
      '7-Meter: Freiwurf im Strafraum oder Foulspiel das klare Torchance verhindert',
      'Passiver Angriff: Schiedsrichter signalisiert → Team muss Torwurf ausführen',
      'Strafbank: 2 Minuten bei Foulspiel oder Unsportlichkeit',
      'Gelbe Karte (Verwarnung), Rote Karte (Spielausschluss)',
    ],
    tip: '60 Min. einstellen, 10 Min. Pause → nach 30 Min. Halbzeit drücken.',
  },
  futsal: {
    name: 'Futsal',
    icon: '⚽',
    structure: '2 × 20 Min. netto + 15 Min. Pause (Uhr stoppt bei Unterbrechungen)',
    periods: 2,
    periodLabel: 'Halbzeit',
    scoring: 'Tore (Ball über die Torlinie)',
    basics: [
      '5 Spieler pro Team (4 Feldspieler + Torwart) auf kleinem Hallenfeld',
      'Kein Abseits beim Futsal',
      'Einwurf mit dem Fuß (Einkick), nicht mit den Händen',
      'Ball muss von Grundlinie bis Gegenpartei 4 Sekunden gespielt werden',
      'Torwart darf keinen Ball von eigenem Mitspieler mit Händen nehmen (Rückpass-Regel)',
      '5-Meter-Strafstoß bei Fouls im Strafraum',
      '10-Meter-Strafstoß für Fouls außerhalb Strafraum (ab 6. Teamfoul pro Halbzeit)',
      'Fliegender Wechsel: Spielerwechsel jederzeit, ohne Spielunterbrechung',
      'Blaue Karte = Auszeit 2 Minuten',
    ],
    tip: '40 Min. einstellen → nach 20 Min. Halbzeit drücken. Auszeit für Spielunterbrechungen nutzen.',
  },
  hockey: {
    name: 'Feldhockey',
    icon: '🏑',
    structure: '4 × 15 Min. + 2 Min. Viertelpausen + 10 Min. Halbzeitpause',
    periods: 4,
    periodLabel: 'Viertel',
    scoring: 'Tore (Schuss aus dem Schusskreis = 14,63-Meter-Halbkreis)',
    basics: [
      '11 Spieler pro Team (10 Feldspieler + Torwart)',
      'Tor zählt nur, wenn Ball aus dem Schusskreis abgespielt wurde',
      'Nur flache Seite des Schlägers darf verwendet werden',
      'Kein Körperkontakt – Stickcheck verboten',
      'Ecke: Schuss über Grundlinie → Strafeck; absichtlich hinter Grundlinie → Strafeck',
      'Strafeck (Penalty Corner): Ball wird von Grundlinie eingeworfen, Schuss nach Ballkontrolle',
      'Penalty: Direktschuss von 7-Meter-Punkt (bei Foul im Kreis)',
      'Gelbe Karte: Temporäre Sperre. Grüne Karte: Verwarnung. Rote Karte: Ausschluss.',
    ],
    tip: '60 Min. einstellen, 4 Viertel à 15 Min. → nach jedem Viertel Halbzeit drücken.',
  },
  floorball: {
    name: 'Floorball',
    icon: '🏒',
    structure: '3 × 20 Min. netto + 10 Min. Pause',
    periods: 3,
    periodLabel: 'Drittel',
    scoring: 'Tore (Ball über Torlinie ins Netz)',
    basics: [
      '5 Spieler pro Team (4 Feldspieler + Torwart)',
      'Torwart: Kein Stock, spielt mit Händen und Beinen',
      'Schläger darf nicht über Knie-Höhe geschwungen werden (Hoher Stock)',
      'Kein Körperkontakt erlaubt (anders als Eishockey!)',
      'Ball darf mit Fuß gespielt werden, aber kein gezielter Torschuss mit Fuß',
      'Torwart darf Ball mit Händen halten, aber nicht in die Spielhälfte werfen',
      '2-Minuten-Strafe: Halten, Fouls, zu hoher Stock',
      '5-Meter-Einwurf: Wenn Ball das Spielfeld verlässt',
      'Freischlag: Bei Regelverstoß → Ball liegt, 3 Sekunden zum Abspielen',
    ],
    tip: '60 Min. einstellen → nach jedem Drittel (20 Min.) Halbzeit drücken.',
  },
  badminton: {
    name: 'Badminton',
    icon: '🏸',
    structure: 'Best of 3 Sätze. Satz bis 21 Punkte. Bei 20:20 bis Zwei-Punkte-Vorsprung (max. 30:29).',
    periods: 3,
    periodLabel: 'Satz',
    scoring: 'Rally-Punkte: Jeder gewonnene Rally gibt Punkt, unabhängig wer aufgeschlagen hat',
    basics: [
      'Einzel: 1 vs. 1. Doppel: 2 vs. 2. Mixed: Mann+Frau vs. Mann+Frau',
      'Aufschlag: Unterhalb der Gürtellinie, Kontakt mit Federbasis zuerst',
      'Aufschlag-Seite: Rechts bei geradem Punktestand, Links bei ungeradem',
      'Federball darf Boden nicht berühren → sofort Punkt für Gegner',
      'Netzberührung: Erlaubt nur mit Schläger beim Return, nicht mit Körper',
      'Doppelberührung: Schläger darf Feder nur einmal berühren',
      'Aufschlag-Fehler: Schläger zu hoch, Fußfehler, in falsches Feld',
      'Seitenwechsel: Nach jedem Satz + im 3. Satz bei 11 Punkten',
    ],
    tip: 'Kein Zeitlimit → Punkte eintragen. Satz vorbei (21 Punkte) → Halbzeit drücken für Satzwechsel.',
  },
  tabletennis: {
    name: 'Tischtennis',
    icon: '🏓',
    structure: 'Best of 5 oder 7 Spiele. Spiel bis 11 Punkte. Zwei-Punkte-Vorsprung nötig.',
    periods: 5,
    periodLabel: 'Spiel',
    scoring: 'Rally-Punkte: Jeder Fehler des Gegners gibt Punkt',
    basics: [
      'Aufschlag: Ball muss mind. 16 cm geworfen werden, hinter der Tischkante',
      'Wechselaufschlag: Alle 2 Punkte wechselt der Aufschlag (bei 10:10 nach jedem Punkt)',
      'Aufschlag muss auf eigene Hälfte und dann auf Gegnerseite aufkommen',
      'Doppel: Ball muss diagonal aufschlagen (Aufschlagfeld beachten)',
      'Kante: Trefft der Ball die seitliche Tischkante → Punkt; auf Kantenschiene → aus',
      'Netzberührung beim Aufschlag (Let): Aufschlag wird wiederholt',
      'Seitenwechsel: Zwischen jedem Spiel. Im Entscheidungsspiel bei 5 Punkten.',
    ],
    tip: 'Kein Zeitlimit → bis 11 Punkte spielen, dann Halbzeit drücken für nächstes Spiel.',
  },
  ultimate: {
    name: 'Ultimate Frisbee',
    icon: '🥏',
    structure: 'Bis 15 Punkte (oder 2 Halbzeiten × 22 Min. mit Cap bei 17). Kein Schiedsrichter – Spirit of the Game.',
    periods: 2,
    periodLabel: 'Halbzeit',
    scoring: 'Punkt: Scheibe in der Endzone fangen',
    basics: [
      '7 Spieler pro Team auf dem Feld (Varianten: 5 für kleinere Felder)',
      'Kein Körperkontakt – Foulregeln durch Spieler selbst angewendet (Spirit of the Game)',
      'Pivot: Werfer darf sich nicht vom Ort bewegen, muss Pivot-Fuß nutzen',
      'Stall Count: Marker zählt bis 10 – Wurf muss vor "10" erfolgen',
      'Turnover: Unvollständiger Pass, Drops, Interception → gegnerisches Team übernimmt',
      'Punkt: Receiver fängt Scheibe in Endzone → sofortiger Punkt',
      'Ziehen (Pull): Beginn jeder Halbzeit und nach jedem Punkt',
      'Foul-Regelung: Gefoulfter Spieler ruft Foul → Spiel stoppt → Discussion → Wiederholung',
      'Zählen als Foul: Kontakt der Arme, Körper, Blockieren des Flusses',
    ],
    tip: 'Bis 15 Punkte oder Zeitlimit → Punkte eintragen, Halbzeit bei 8 Punkten oder Zeitmitte.',
  },
  tchoukball: {
    name: 'Tchoukball',
    icon: '🎯',
    structure: '3 × 15 Min. + 5 Min. Pausen',
    periods: 3,
    periodLabel: 'Periode',
    scoring: 'Punkt: Ball prallt von Rahmen und landet im Spielfeld ohne gefangen zu werden',
    basics: [
      '7 Spieler pro Team. Zwei Rahmen (Rebound-Frames) an beiden Enden',
      'Kein Körperkontakt erlaubt – weder in Angriff noch Verteidigung',
      'Werfen auf eigenen oder gegnerischen Rahmen erlaubt',
      '3 Schritte und 3 Pässe pro Angriff bevor auf Rahmen geworfen wird',
      'Verbotszone (3-Meter-Halbkreis): Niemand darf in die Zone',
      'Punkt: Ball vom Rahmen abprallen, landet im Feld → Angreifer erhält Punkt',
      'Negativpunkt: Ball landet im Aus, in Verbotszone, Fänger fängt ihn → Gegner erhält Punkt',
      'Wechsel: Fliegend, jederzeit möglich',
    ],
    tip: '45 Min. einstellen, 3 Perioden → nach 15 Min. jeweils Halbzeit drücken.',
  },
  faustball: {
    name: 'Faustball',
    icon: '🏅',
    structure: 'Best of 3 oder 5 Sätze. Satz bis 11 Punkte (Zwei-Punkte-Vorsprung bis max. 15).',
    periods: 3,
    periodLabel: 'Satz',
    scoring: 'Punkt wenn Ball im gegnerischen Feld aufkommt oder Gegner Fehler macht',
    basics: [
      '5 Spieler pro Team. Gespielt über ein gespanntes Seil oder einen Pfosten (1,80–2,00 m Höhe)',
      'Ball darf max. zweimal den Boden berühren bevor er zurückgespielt wird',
      'Jeder Spieler darf den Ball einmal schlagen (2 Ballkontakte max.)',
      'Einzel-Berührung: Nur mit Faust oder Arm (kein Körperkontakt mit anderen Körperteilen)',
      'Aufschlag: Werfer schmeißt Ball hoch und schlägt ihn über Seil in Gegenfeld',
      'Aufschlag muss nach hinten ins Feld der Gegner gehen (nicht ins eigene)',
      'Netz/Seilberührung: Punkt für Gegner',
    ],
    tip: 'Kein Zeitlimit → bis 11 Punkte spielen, dann Halbzeit drücken für nächsten Satz.',
  },
  brennball: {
    name: 'Brennball',
    icon: '🔥',
    structure: '2 Halbzeiten. Meist 20 Min. oder bis alle Schläger einmal dran waren.',
    periods: 2,
    periodLabel: 'Halbzeit',
    scoring: 'Läufer erreicht Brennmal = 1 Punkt für Schlagmannschaft',
    basics: [
      'Schlagmannschaft: Ein Spieler schlägt Ball, dann rennen alle zur Brennstelle und zurück',
      'Wurfmannschaft: Wirft Ball und versucht Läufer abzuschlagen oder Base zu treffen',
      'Brennmal: Fangpfosten oder Markierung, die Läufer umrunden müssen',
      'Abschlagen: Läufer wird abgeschlagen = ein Aus für die Schlagmannschaft',
      'Aus: Nach x Outs (variabel, meist 3) → Seiten tauschen',
      'Fangball: Wird Ball direkt gefangen → Seiten tauschen sofort',
      'Zählen: Läufer zählt Punkt wenn er Brennmal berührt und sicher zurück ist',
      'Heimlauf: Läufer schafft Brennmal + Rückweg in einem Durchgang = 1 Punkt',
      'Variante: Läufer darf am Brennmal warten und beim nächsten Schlag laufen',
    ],
    tip: '40 Min. einstellen → nach 20 Min. Halbzeit drücken → Schlag-/Wurfmannschaft tauscht.',
  },
  prellball: {
    name: 'Prellball',
    icon: '🏐',
    structure: 'Best of 3 Sätze. Satz bis 15 Punkte (Zwei-Punkte-Vorsprung).',
    periods: 3,
    periodLabel: 'Satz',
    scoring: 'Punkt: Ball landet im Feld des Gegners oder Gegner macht Fehler',
    basics: [
      '2–6 Spieler pro Team auf kleinem Spielfeld (Netz ca. 70–80 cm hoch)',
      'Ball darf nur auf den Boden der eigenen Seite geprellt werden (Unterschied zu Volleyball)',
      'Nach dem Prellen muss der Ball über das Netz gespielt werden',
      'Jeder Spieler darf Ball einmal berühren (prellen oder direkt spielen)',
      'Ball darf zwischen 2 Spielern einmal hin und her gespielt werden (1 Prellen + 1 Direkt)',
      'Aufschlag von der Grundlinie – Ball muss auf eigene Seite, dann über Netz',
      'Netzberührung: Aus → Punkt für Gegner',
      'Ball außerhalb Feld: Punkt für Gegner',
    ],
    tip: 'Kein Zeitlimit → bis 15 Punkte spielen, dann Halbzeit drücken für nächsten Satz.',
  },
  schlagball: {
    name: 'Schlagball',
    icon: '⚾',
    structure: '2 Hälften. Häufig begrenzt durch Anzahl der Outs oder Spielzeit.',
    periods: 2,
    periodLabel: 'Halbzeit',
    scoring: 'Punkte durch Erreichen der Bases und Home Base',
    basics: [
      'Ähnlich wie Baseball, vereinfachte Variante für den Schulsport',
      'Schlagmannschaft: Schläger schlägt geworfenen Ball, rennt zu Base(s)',
      'Wurfmannschaft: Wirft Ball und versucht Schläger auszumachen',
      'Bases: 3 oder 4 Bases im Feld; Heimlauf = vollständiger Rundlauf = Punkt',
      'Out: Direkt gefangener Ball; Schläger am Mal abschlagen; 3 Fehlschläge',
      'Wechsel: Nach x Outs (meist 3) tauschen die Teams',
      'Teamgröße: 8–12 Spieler pro Team',
    ],
    tip: '40 Min. einstellen → nach 20 Min. Halbzeit drücken → Teams wechseln die Seiten.',
  },
  staffellauf: {
    name: 'Staffellauf',
    icon: '🎿',
    structure: 'Stoppuhr-Modus. Zeitmessung pro Läufer oder Gesamtzeit.',
    periods: 1,
    periodLabel: 'Lauf',
    scoring: 'Schnellste Gesamtzeit der Staffel gewinnt',
    basics: [
      'Teams bestehen aus 4 Läufern (klassische Staffel)',
      'Übergabezone: Stab muss innerhalb festgelegter Zone übergeben werden (20m-Zone)',
      'Fallenlassen des Stabs: Läufer muss zurück und Stab aufheben',
      'Frühstart: Übergabe vor Zone = Disqualifikation',
      'Wechsel: Empfangender Läufer startet, wenn gebender Läufer in Zone ist',
      '4 × 100m (Sprint-Staffel), 4 × 400m (Mittelstrecken-Staffel)',
      'Sporthallen-Variante: Gegenstände übergeben statt Stab',
    ],
    tip: 'Tools-Screen → Stoppuhr mit Lap-Funktion. Jede Übergabe als Lap markieren.',
  },
};

export function getRule(key) {
  return RULES[key] || null;
}

export function getAllRules() {
  return Object.entries(RULES).map(([key, rule]) => ({ key, ...rule }));
}
