import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / 'content' / 'sportmodes' / 'exercises.draft.json'

SPEC = {
'football': ('Fußball', '⚽', [
('Dribbling-Parcours','Dribbling','Ballführung unter Richtungswechseln'), ('Innen-/Außenrist-Pass','Passen','Passgenauigkeit und beidfüßige Technik'), ('Dreiecks-Passen','Passen','Freilaufbewegung und Passwinkel'), ('Annahme in Bewegung','Ballannahme','Erste Ballberührung in den freien Raum'), ('Rondo 4 gegen 1','Ballbesitz','Schnelle Entscheidungen unter Gegnerdruck'), ('Rondo 5 gegen 2','Ballbesitz','Ballzirkulation und Kommunikation'), ('Torschuss nach Querpass','Torschuss','Abschluss nach Laufweg zum ersten Pfosten'), ('Torschuss nach Dribbling','Torschuss','Mutiger Abschluss aus dem Dribbling'), ('Finte und Torabschluss','Torschuss','Täuschung vor dem Abschluss'), ('1 gegen 1 offensiv','Zweikampf','Gegner ausspielen und Raum gewinnen'), ('1 gegen 1 defensiv','Zweikampf','Gegner nach außen lenken und Ball erobern'), ('2 gegen 1 Überzahl','Angriff','Überzahl erkennen und gemeinsam nutzen'), ('2 gegen 2 mit Umschalten','Umschalten','Schneller Wechsel zwischen Angriff und Abwehr'), ('Passfolge mit Klatschen','Passen','Passschärfe und Anschlussbewegung'), ('Steilpass und Lauf','Passen','Timing von Pass und Tiefenlauf'), ('Ballmitnahme unter Druck','Ballannahme','Ball sichern und offene Seite finden'), ('Flanken und Abschluss','Torschuss','Flanken aus dem Lauf verwerten'), ('Kopfballtechnik mit Zuspiel','Kopfball','Sicheres Timing bei hohen Bällen'), ('Torwart-Grundstellung','Torwart','Grundposition und sicheres Fangen'), ('Torwart-Fußarbeit','Torwart','Seitliche Bewegung vor dem Torabschluss'), ('Schnelligkeit mit Ball','Athletik','Antritt und Ballkontrolle verbinden'), ('Sprint ohne Ball','Athletik','Explosiver Antritt auf Kommando'), ('Reaktionsfarben mit Ball','Koordination','Reaktion und enge Ballführung'), ('Passdreieck mit Gegner','Passen','Orientierung vor der Ballannahme'), ('Kleinfeld 3 gegen 3','Spielform','Viele Ballaktionen und mutiges Spiel'), ('Kleinfeld 4 gegen 4','Spielform','Breite und Tiefe im Spiel nutzen'), ('Überzahl auf zwei Tore','Angriff','Schnelle Seitenverlagerung'), ('Konter nach Ballgewinn','Umschalten','Erster Pass nach Ballgewinn nach vorne'), ('Pressing-Auslöser','Abwehr','Gemeinsames Anlaufen im richtigen Moment'), ('Abwehrkette verschieben','Abwehr','Abstände halten und Räume schließen'), ('Standards: Eckball kurz','Standards','Einfache Laufwege bei Eckbällen')]),
'handball': ('Handball', '🤾', [
('Passen und Fangen in Bewegung','Passen','Sicheres Zuspiel bei hohem Tempo'), ('Dreierpass mit Kreuzung','Passen','Kreuzbewegung und Blickkontakt'), ('Prellparcours','Ballführung','Kontrolliertes Prellen mit Richtungswechsel'), ('Sprungwurf aus dem Anlauf','Wurf','Absprung und zielgenauer Wurf'), ('Wurfvarianten auf Ziele','Wurf','Wurfgenauigkeit in verschiedene Ecken'), ('Täuschung und Durchbruch','Angriff','Körperfinte und dynamischer Durchbruch'), ('1 gegen 1 im Korridor','Zweikampf','Richtiges Timing im Angriff'), ('Abwehrgrundstellung','Abwehr','Seitliches Verschieben und Abstand'), ('Abwehr 2 gegen 2','Abwehr','Übergabe und Übernahme'), ('Kreisläufer anspielen','Angriff','Passfenster zum Kreis erkennen'), ('Gegenstoß in Wellen','Umschalten','Schnelles Umschalten nach Ballgewinn'), ('Torwart: Winkel verkürzen','Torwart','Positionierung zur Wurfarmseite'), ('Torwart: Reaktion','Torwart','Reaktion auf kurze Würfe'), ('Überzahl 3 gegen 2','Angriff','Zusatzpass und freie Wurfchance'), ('Kleinfeld-Handball 4 gegen 4','Spielform','Entscheidungen und Bewegung ohne Ball')]),
'volleyball': ('Volleyball', '🏐', [
('Pritschen am Partner','Technik','Saubere Fingerhaltung und kontrolliertes Zuspiel'), ('Baggern am Partner','Technik','Plattform stabil ausrichten'), ('Pritschen in Bewegung','Technik','Zuspiel nach seitlicher Bewegung'), ('Baggern nach Laufweg','Technik','Ball unter Zeitdruck kontrollieren'), ('Aufschlag von unten','Aufschlag','Sicherer Einsteigeraufschlag'), ('Aufschlag von oben','Aufschlag','Treffpunkt und Ganzkörpereinsatz'), ('Aufschlagzielzonen','Aufschlag','Platzierte Aufschläge in freie Zonen'), ('Dreierkette Annahme','Annahme','Kommunikation und Annahmedreieck'), ('Annahme-Zuspiel-Angriff','Spielaufbau','Drei Kontakte als feste Folge'), ('Angriffsschlag ohne Sprung','Angriff','Anlauf und Schlagarm koordinieren'), ('Angriffsschlag mit Sprung','Angriff','Absprung und sicherer Treffpunkt'), ('Block-Grundtechnik','Block','Handposition und Landung am Netz'), ('Abwehrbagger','Abwehr','Tief stehen und Angriff abwehren'), ('2 gegen 2 über das Netz','Spielform','Freie Räume erkennen und anspielen'), ('3 gegen 3 mit Pflichtkontakt','Spielform','Rally verlängern und gemeinsam sichern')]),
'basketball': ('Basketball', '🏀', [
('Ballhandling im Stand','Ballführung','Sichere Kontrolle mit beiden Händen'), ('Dribbling mit Richtungswechsel','Ballführung','Crossover und Tempowechsel'), ('Dribbling-Parcours','Ballführung','Ballkontrolle unter wechselnden Aufgaben'), ('Brustpass und Fangen','Passen','Präzises Zuspiel auf Brusthöhe'), ('Bodenpass','Passen','Pass unter den Armen der Abwehr'), ('Passdreieck mit Nachlaufen','Passen','Pass und Anschlussbewegung'), ('Korbleger rechts','Wurf','Schrittfolge und Abschluss rechts'), ('Korbleger links','Wurf','Schrittfolge und Abschluss links'), ('Standwurf aus fünf Positionen','Wurf','Wurftechnik und Balance'), ('Freiwurf-Routine','Wurf','Konstante Vorbereitung und Konzentration'), ('Sprungwurf nach Pass','Wurf','Schnelles Fangen und Hochgehen'), ('1 gegen 1 vom Flügel','Zweikampf','Erster Schritt und Abschluss'), ('Closeout und Verteidigung','Abwehr','Kontrolliert anlaufen und Weg versperren'), ('Rebound-Boxout','Abwehr','Körper zwischen Gegner und Korb bringen'), ('3 gegen 2 Fastbreak','Umschalten','Überzahl mit guter Breite ausspielen')])}

SETUP = {'football':'Hütchen, Bälle und zwei Minitore; Feld 20 × 25 m; 6–12 Personen.', 'handball':'Handbälle, Hütchen und Tor; Feld 20 × 25 m; 6–12 Personen.', 'volleyball':'Volleyball, Netz und Markierungsteller; halbes Feld; 4–12 Personen.', 'basketball':'Bälle, Hütchen und ein Korb; halbes Feld; 4–10 Personen.'}
STEPS = {'football':['In zwei bis drei gleich große Gruppen einteilen und Ablauf ohne Gegner vormachen.','Übung zunächst mit kontrolliertem Tempo durchführen; danach Tempo und Entscheidungsdruck erhöhen.','Nach jeder Serie Rollen und Startpositionen wechseln.'], 'handball':['Paare oder Kleingruppen bilden und Pass-/Laufweg zunächst ohne Gegner zeigen.','Mit sicherem Grundtempo starten und anschließend Abwehrdruck oder Zeitvorgabe ergänzen.','Nach jeder Serie Positionen und Wurfseite wechseln.'], 'volleyball':['Gruppen bilden und Kommunikationsruf festlegen.','Mit kontrollierter Zuspielhöhe beginnen und danach Bewegung oder Zielzonen ergänzen.','Nach jeder Serie rotieren, damit alle Rollen erprobt werden.'], 'basketball':['Paare oder Kleingruppen bilden und Laufwege ohne Verteidigungsdruck einüben.','Mit kontrolliertem Tempo starten; danach Zeit-, Ziel- oder Gegnerdruck erhöhen.','Nach jeder Serie Seite, Rolle und Startposition wechseln.']}
VARIATIONS = {'football':['Leichter: größere Abstände und passiver Gegner.','Schwerer: kleineres Feld, schwächerer Fuß oder Zeitlimit.'], 'handball':['Leichter: größere Abstände und passiver Abwehrspieler.','Schwerer: kleineres Feld, schwächere Hand oder Zeitlimit.'], 'volleyball':['Leichter: Ball fangen und kontrolliert weiterwerfen.','Schwerer: kleinere Zielzone, Bewegung vor Kontakt oder Pflichtfolge.'], 'basketball':['Leichter: Verteidigung passiv und näher am Korb.','Schwerer: schwächere Hand, engeres Feld oder Abschluss unter Zeitdruck.']}
SAFETY = {'football':'Abstände zwischen Gruppen sichern, keine Grätschen in der Übung; bei Schmerz oder Schwindel sofort pausieren.', 'handball':'Wurf- und Laufwege trennen, Körperkontakt kontrollieren, Torraum freihalten; bei Schmerz oder Schwindel pausieren.', 'volleyball':'Unter dem Netz nicht kreuzen, sichere Landung mit gebeugten Knien; bei Schulter- oder Fingerschmerz pausieren.', 'basketball':'Laufwege und Korbbereich freihalten, nicht unter springende Personen laufen; bei Schmerz oder Schwindel pausieren.'}

def make_exercise(sport, n, item):
    title, category, goal = item
    return {'id':f'{sport}-{n:02d}', 'sportId':sport, 'modeId':f'{sport}-uebungen', 'title':title, 'category':category, 'goal':goal, 'setup':SETUP[sport], 'steps':STEPS[sport], 'variations':VARIATIONS[sport], 'safety':SAFETY[sport]}

sports=[]
for sport,(name,icon,items) in SPEC.items():
    sports.append({'sportId':sport, 'name':name, 'icon':icon, 'modeId':f'{sport}-uebungen', 'modeName':'Übungen', 'exercises':[make_exercise(sport,i+1,item) for i,item in enumerate(items)]})
data={'schemaVersion':1, 'status':'draft', 'description':'Fachlicher Content-Entwurf für sportartspezifische Übungsmodi. Allgemeinsport-Content bleibt in content/games unverändert.', 'sports':sports}
OUT.parent.mkdir(parents=True, exist_ok=True)
OUT.write_text(json.dumps(data, ensure_ascii=False, indent=2)+'\n')
print(json.dumps({s['sportId']:len(s['exercises']) for s in sports}, ensure_ascii=False))
